"""3D terrain reconstruction: turn an (enhanced) DEM + optionally an
(enhanced) 2D optical image into a textured 3D surface, exported both as a
static rendering and as a standard mesh file (OBJ) that can be opened in any
3D viewer (Blender, MeshLab, Bhuvan-style WebGL viewers, etc.).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


def dem_to_mesh(
    dem: np.ndarray,
    pixel_size_m: float = 1.0,
    z_exaggeration: float = 1.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert a DEM grid into a triangle mesh.

    Returns:
        vertices: (H*W, 3) float32 array of (x, y, z) in meters.
        faces: (num_triangles, 3) int32 array of vertex indices.
    """
    h, w = dem.shape
    ys, xs = np.mgrid[0:h, 0:w]
    xs = xs.astype(np.float32) * pixel_size_m
    ys = ys.astype(np.float32) * pixel_size_m
    zs = dem.astype(np.float32) * z_exaggeration
    vertices = np.stack([xs.ravel(), ys.ravel(), zs.ravel()], axis=-1)

    faces = []
    for y in range(h - 1):
        row0 = y * w
        row1 = (y + 1) * w
        idx = np.arange(w - 1)
        v00 = row0 + idx
        v01 = row0 + idx + 1
        v10 = row1 + idx
        v11 = row1 + idx + 1
        tri1 = np.stack([v00, v10, v01], axis=-1)
        tri2 = np.stack([v01, v10, v11], axis=-1)
        faces.append(tri1)
        faces.append(tri2)
    faces = np.concatenate(faces, axis=0).astype(np.int32)
    return vertices, faces


def save_obj(
    path: str | Path,
    vertices: np.ndarray,
    faces: np.ndarray,
    texture: np.ndarray | None = None,
) -> None:
    """Write a mesh to Wavefront OBJ format, with optional per-vertex UVs for
    draping an (enhanced) optical image over the terrain as a texture."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = ["# Generated by satellite_enhance.utils.terrain3d", "o terrain"]
    for v in vertices:
        lines.append(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}")

    if texture is not None:
        # UVs assume vertices were generated row-major over an h x w grid,
        # matching dem_to_mesh's ordering.
        gh, gw = _infer_grid_shape(vertices)
        for j in range(gh):
            for i in range(gw):
                u = i / max(gw - 1, 1)
                v = 1.0 - j / max(gh - 1, 1)
                lines.append(f"vt {u:.6f} {v:.6f}")

    use_uv = texture is not None
    for f in faces:
        if use_uv:
            lines.append(f"f {f[0]+1}/{f[0]+1} {f[1]+1}/{f[1]+1} {f[2]+1}/{f[2]+1}")
        else:
            lines.append(f"f {f[0]+1} {f[1]+1} {f[2]+1}")

    path.write_text("\n".join(lines))


def _infer_grid_shape(vertices: np.ndarray) -> tuple[int, int]:
    """Recover (rows, cols) of a row-major grid mesh from its flattened vertices."""
    n = len(vertices)
    first_y = vertices[0, 1]
    w = int(np.sum(np.isclose(vertices[:, 1], first_y)))
    h = n // w
    return h, w


def render_3d_preview(
    dem: np.ndarray,
    out_path: str | Path,
    texture: np.ndarray | None = None,
    z_exaggeration: float = 2.0,
    elev: float = 45.0,
    azim: float = -60.0,
    title: str = "3D Terrain Reconstruction",
    max_grid: int | None = None,
) -> None:
    """Render a static 3D surface plot (matplotlib) for quick visual QA,
    optionally colored by a co-registered optical image.

    Args:
        max_grid: if set, decimate the mesh so neither side exceeds this
            many vertices before plotting. matplotlib's 3D surface renderer
            scales poorly with vertex count (a full-resolution 500x500 grid
            takes several seconds per frame); decimating to ~150-200 keeps
            interactive multi-angle previews fast while barely changing the
            rendered appearance at typical preview sizes.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if max_grid is not None:
        step = max(1, max(dem.shape) // max_grid)
        dem = dem[::step, ::step]
        if texture is not None and texture.shape[:2] == (dem.shape[0] * step, dem.shape[1] * step):
            texture = texture[::step, ::step]

    h, w = dem.shape
    ys, xs = np.mgrid[0:h, 0:w]

    fig = plt.figure(figsize=(9, 7))
    ax = fig.add_subplot(111, projection="3d")

    facecolors = None
    if texture is not None:
        tex = texture
        if tex.shape[:2] != dem.shape:
            from PIL import Image

            tex_img = Image.fromarray((np.clip(tex, 0, 1) * 255).astype(np.uint8))
            tex_img = tex_img.resize((w, h), Image.BILINEAR)
            tex = np.asarray(tex_img).astype(np.float32) / 255.0
        facecolors = tex

    surf_kwargs = dict(rstride=1, cstride=1, linewidth=0, antialiased=True)
    if facecolors is not None:
        ax.plot_surface(xs, ys, dem * z_exaggeration, facecolors=facecolors, **surf_kwargs)
    else:
        ax.plot_surface(xs, ys, dem * z_exaggeration, cmap="terrain", **surf_kwargs)

    ax.set_title(title)
    ax.set_xlabel("X (px)")
    ax.set_ylabel("Y (px)")
    ax.set_zlabel("Elevation (m, exaggerated)")
    ax.view_init(elev=elev, azim=azim)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=140, bbox_inches="tight")
    plt.close(fig)
